### PR TITLE
PreInstall

### PR DESCRIPTION
**Pull request by Tynnee**

### CODE REVIEW

**Comment by kenny-hibino** [comment]
@Tynnee could you explain the reason for this PR?

**Comment by Tynnee** [comment]
hey sorry.... was an error. pls disregard

**Comment by Tynnee** [comment]
hey i bn tryna deploy to the app with heroku but build keeps failing. think u could help me out?

**Comment by kenny-hibino** [comment]
I currently don't have enough bandwidth to work on this project, unfortunately, but you can definitely create an issue in this repository to seek some help!

**Pull request closed without merging**
